import React from 'react'

export const JobsData = {
    jobscard: [
        {
            id: 1,
            jobsTitle:"Frontend Developer",
            salary: 5000,
            jobLocation:"Cairo, Egypt",
            jobType:"Remote",
            jobDescription1:"A FullTime Job As a front-end software developer, you'll be responsible for coding our innovative designs and layouts into well-written, best-practice JavaScript components. Senior front-end development responsibilities include refining our client-side architecture, being a role model for maintainable and testable code, and implementing working web-based solutions from mockups.",
            companyLogo:"",
            companyName:"Dsquares",
            aboutus:"Dsquares specializes in offering loyalty programs that bring our clients closer to their consumers. Through our different range of solutions, we deliver an end-to-end experience, managing and executing all technical, operational, and commercial aspects of our customers’ loyalty programs. From full loyalty programs, couponing solutions to interactive directory services, coupled with an extensive network of merchants, Dsquares serves some of the most loved brands in the region.",
            jobDescription2:" Integrate independent HTML/CSS into existing code to produce fully functioning features. Develop and maintain highly engineered, responsive, and cross-browser compatible front-end user interface code. Integrate backend components. Mentor developers and advocate for high standards throughout the development process. Stay plugged into emerging UI/UX technologies/industry trends and apply them into operations and activities. Cooperate with web designers to match visual design intent. Lead test automation efforts.  Create website layouts and user interface by using standard HTML/CSS practices from designs/mockups. ",
            jobrequirements:"-A keen eye for detail and love of delivering beautiful user experiences. -Ability to write modular, scalable, and clean code. -Self-motivated and driven to improve. -Comfortable to work in a fast-paced environment. -Strong organizational skills to juggle multiple tasks within the constraints of deadlines. -Technical Skills: HTML, CSS, JavaScript, jQuery, Bootstrap, SaaS, Angular/React. ",

        }, 
        {
            id: 2,
            jobsTitle:"Backend Developer",
            salary:6000,
            jobLocation:"Cairo, Egypt",
            jobType:"On-Site",
            jobDescription1:"A FullTime Job As a  Backend Developer-NodeJs, This role will be responsible for Javascript/Typescript development while providing expertise in the full software development life cycle, from concept and design to testing.",
            aboutus:"We believe financial services should be more accessible, that’s why we started Axis. A fully interoperable mobile wallet which enables users to send and receive money from any mobile wallet in Egypt, pay their bills, buy anything online with a virtual Visa card, or scan any QR code to pay for anything in-person. Axis empowers small businesses with simplified digital payments to compete & grow. Our digital banking platform enables small businesses to seamlessly manage payments to employees and suppliers. Small businesses can now send salaries, reimbursements and instantly pay their suppliers on any mobile wallet in Egypt.",
            jobDescription2:"We are looking for a smart and skilled Backend Developer-NodeJs, This role will be responsible for Javascript/Typescript development while providing expertise in the full software development life cycle, from concept and design to testing.",
            companyLogo:"",
            companyName:"Axis",
            jobrequirements:"Proficient in TypeScript/Javascript Strong Experience with Node.js frameworks like ( Express - Nestjs ) Strong experience with performance tuning, debugging, and monitoring. Strong understanding of RESTful API design principles. Hands-on experience with microservices architecture. Hands-on experience with MongoDB or similar NoSQL databases. Familiarity with CI/CD principles and active involvement in issue resolution. Familiarity with either of: Go (Golang) or gRPC or Java is a plus. Familiarity with Single-Sign-on or token-based authentication (Rest, JWT, Auth). Familiarity with Agile methodologies and practices. ",
        },
        {
            id: 3,
            jobsTitle:"Network Engineer",
            salary: 7000,
            jobLocation:"Cairo, Egypt",
            jobType:"On-Site",
            jobDescription1:"Bitrion is seeking a skilled a FullTime Job As  Network Administrator responsible for maintaining and enhancing our network infrastructure. The ideal candidate will design and support network systems to optimize performance and provide troubleshooting in Linux and Windows environments.",
            companyLogo:"",
            companyName:"Bitrion",
            jobDescription2:"Qualifications: Bachelor's Degree in Computer Science or related area 2 - 4 years' of experience with network administration in a Linux or Windows environment Holder of valid Network & Security certifications such as CCNA, CCNP, CCIE, RHCSA, RHCE ,CEH . ",
            aboutus:"The ideal candidate will be responsible for maintaining and intermittently improving our current network configuration and infrastructure. You will design our revamped network infrastructure with the goal of maximizing our network performance. You will also provide troubleshooting and configuration support by using your strong technical skills in Linux and Windows environments and IP networking.  ",
            jobrequirements:" Proficient in implementing IGP/EGP, BGP & VRF for both IPV4 & IPV6 protocols in Cisco networks . Deeply Knowledge of IP networking fundamentals. Deeply Knowledge of TCP/IP fundamentals. Deeply Knowledge of VPN fundamentals . Strong knowledge with Linux OS and administration .Skilled in securing IP core networks against various risks, including Net-flow/Fastnetmon DOS handling .SDWAN networking knowledge or experince .Strong knowledge of scripting and automation using languages like Python . ",
        },
        {
            id: 4,
            jobsTitle:"FullStack Developer",
            salary: 10000,
            jobLocation:"Cairo, Egypt",
            jobType:"Remote",
            jobDescription1:"Join Vezeeta’s Engineering Team! We're seeking a skilled tech engineer for a part-time role to design, develop, and integrate cutting-edge solutions using C#, NodeJS, and more. Drive innovation in health-tech with us—apply now!",
            companyLogo:"",
            companyName:"Vezeeta",
            jobDescription2:"- Build robust and scalable software in C# and NodeJS for applications, APIs, services and middle-ware components as well as modifications of existing software. - Design and create services and define system architecture for your projects, and contribute and provide feedback to other team members.- Enhance code quality through writing unit tests, automation and performing code reviews.- Brainstorm for ideas to our technologies, platform and products and see your ideas grow and flourish.- Work with the product and design teams to understand end-user requirements, formulate use cases, and then translate that into a pragmatic and effective technical solution. - Solve challenging technical problems and successfully deliver results on schedule.- Developing new and maintaining existing user-facing features- Write client-side code for web-based applications, create fast, easy-to-use, high volume production applications. - Ensuring the technical feasibility of UI/UX designs.- Contribute to presentation layer standards and practices.- Contribute to testing and implementation approach for presentation layer.- Prototype future interfaces.- Collaborating closely with the product team and other team members and stakeholders .",
            aboutus:"The engineering department at Vezeeta is having highly skilled technology engineer with business knowledge and technical expertise to implement strategies, evaluate processes, and build upon an infrastructure that supports the ever-changing needs of our customers. In this role, you will work with different systems, designing, developing, and integrating them at every stage of the life cycle. If you are reliable in delivering mission-critical solutions with the goals of accessibility, optimization, and security, you could be our ideal candidate. This is a position that will see you gain experience and skills in a wide range of areas as well as working at the forefront of the health-tech industry.",
            jobrequirements:"- Bachelor’s degree with a concentration in Computer Science, Computer Engineering or related subject from a reputable university is preferred - 2+ years of experience in Back-end engineering.- 2+ years of experience in developing highly interactive web applications with modular, reusable JavaScript. - Strong knowledge and first-hand experience in C#, MySQL and SQL Server Development. - Experience in Bootstrap or other UI framework, experience in SASS, Gulp and Bower - Strong knowledge and first-hand experience in web applications; modular and reusable JavaScript. SEO friendly HTML and CSS, ReactJS. - Experience in Microservices architecture, RabbitMQ, Node.js, Redis, Memcache or Varnish is a big plus. - Knowledge in Object-Oriented Design Patterns- Knowledge in Enterprise Integration Patterns is a high plus- Strong communication skills and ability to work in a dynamic environment. - Industry experience is a plus",
        },
        {
            id: 5,
            jobsTitle:"Senior DevOps Engineer",
            salary: 8000,
            jobLocation:"Cairo, Egypt",
            jobType:"Remote",
            jobDescription1:"Join us as a DevOps Engineer! Manage and optimize large-scale Linux server environments, automate workflows, and ensure high availability of services. Enjoy competitive pay, remote work, and flexible hours. Apply now!",
            companyLogo:"",
            companyName:"Daftra - دفترة",
            jobDescription2:"Responsibilities: Manage & Handel large-scale Linux server environments including deployment, administration, networking, performance monitoring/tuning, security hardening, troubleshooting, and production operations. Install, configure, monitor, and maintain production and testing servers and services (Linux, Docker, Apache, Nginx, PHP, Mysql, Haproxy) Scale up and set up our cloud infrastructure to fit the ongoing requirements for our fast-growing products (EC2, S3, Load Balancers) Deploy, configure and manage large-scale MySQL, Backups, and replications (Mainly Mysql) Setup monitoring and tracking to all running services and maintain them to maximize the uptime of the service Architect, design and implement secure build and deploy automation solutions, enhance, and maintain existing automation (Jenkins, Bitbucket) Provide environments/operations triage support to troubleshoot & resolve build and deploy issues encountered in production, development, and test environments.",
            aboutus:"TDaftra is a comprehensive and secure online cloud system designed to manage various types of organizations, whether commercial or service-oriented, and supports over 50 different business sectors. Daftra's cloud services operate 24/7 with a 99.9% uptime guarantee, thanks to our secure servers located in multiple countries, ensuring fast and safe access to your company data anytime, anywhere, and across various devices and platforms. Born from the extensive experience of our company, Daftra offers a complete ERP solution tailored to the rapidly growing and digitally transforming Arab market using cloud computing technology. Regardless of your business field, Daftra can be fully customized to meet your specific needs, from simple invoicing to complex accounting tasks, precise inventory management, customer relations, team organization, and even a full human resources system for payroll management—all integrated into one automated system to reduce costs, increase profits, and save time.he ideal candidate will be responsible for maintaining and intermittently improving our current network configuration and infrastructure. You will design our revamped network infrastructure with the goal of maximizing our network performance. You will also provide troubleshooting and configuration support by using your strong technical skills in Linux and Windows environments and IP networking.  ",
            jobrequirements:" The Perfect candidate must have a full experience of the following: Graduate from computer science, Engineering or any other related field. 5+ Years of Experience as a DevOps Engineer Flexible with Working hours as he will work day and night. Linux Server Administration Docker Building, Running, and Configuration Apache and Nginx Server Configuration Large Scale MySQL Database Configuration, Maintenance, Replica, Backups, and restore AWS Cloud Services (Ec2, S3, ELB, Budgeting, Auto Scaling)",
        },
        {
            id: 6,
            jobsTitle:"Cyber Security Cyber Risk - Associate",
            salary: 11000,
            jobLocation:"Cairo, Egypt",
            jobType:"On-Site",
            jobDescription1:"Join PwC as a Cyber Security Senior Associate! Tackle cyber risks for top companies, conduct security assessments, and develop policies in a dynamic, global environment. Great opportunities for growth and international experience. Apply now!",
            companyLogo:"",
            companyName:"PwC Middle East",
            jobDescription2:" Cyber security is one of the defining topics of our age, and cyber risk represents one of the most significant strategic risks to PwC’s clients. In a recent PwC survey, it remains the top risk in the minds of CEO’s globally, with 91% of UK CEOs rating it as a significant concern. Businesses are changing rapidly, facing disrupted supply chains, rapidly changing workforces and accelerating digital transformation on an unprecedented scale. At PwC we help our clients transform, and our cyber security practice enables them to execute that transformation securely and to become more resilient to cyber security threats. Our cyber security practice operates nationally, and serves clients holistically with strategy, risk and governance advice, and with deep technical implementation and assurance expertise. degree in Computer Science or related area 2 - 4 years' of experience with network administration in a Linux or Windows environment Holder of valid Network & Security certifications such as CCNA, CCNP, CCIE, RHCSA, RHCE ,CEH . ",
            aboutus:"ThPwC is one of the world’s largest providers of assurance, tax, and business consulting services. We believe that the best outcomes are achieved through close collaboration with our clients and the many stakeholder communities we serve. So every day, 364,000 PwC people in 158 countries work hard to build strong relationships with others and understand the issues and aspirations that drive them. At PwC, we measure success by our ability to create the value that our clients, our people and the wider investing public are looking for. As a one of the world’s largest professional services firms, PwC can offer a wide range of services and brings variety of skills and experience to bear on your issues.e ideal candidate will be responsible for maintaining and intermittently improving our current network configuration and infrastructure. You will design our revamped network infrastructure with the goal of maximizing our network performance. You will also provide troubleshooting and configuration support by using your strong technical skills in Linux and Windows environments and IP networking.  ",
            jobrequirements:"Good knowledge and/or a proven record of success in regard to Governance, Risk and Compliance (GRC), Good knowledge of common cyber security frameworks such as ISO 27001, NIST CSF & PCI DSS ,Experience in executing cyber security audits and assessments, Experience in defining cyber security policies, standards and procedures ,At least 1 year of relevant work experience for Associate grade, At least 3 years of relevant work experience for Senior Associate grade ,Open minded seeking innovative solutions ,Ability to work within a fast-paced & unstructured environment ,Ability to interact efficiently with senior members of the firm across multiple time zones ,Self-starter attitude.",
        },
    ]

}

export default JobsData
